module.exports = {
  subjectList: [
    "Principal",
    "EVS",
    "General English",
    "Intro to Law",
    "Economics",
    "Political Science",
    "Contract II",
    "History",
    "Crime Law",
    "Environmental Law",
    "Family Law",
    "Company Law",
    "Labour Law",
    "Law of Evidence",
    "Administrative Law",
    "Human Rights",
    "Child and Law",
    "Land Law",
    "DPC",
    "Trademark Law",
    "Law Medicine",
    "International Trade Law",
    "Taxation",
    "Professional Ethics",
  ],
  trSubjectList: [
    "Principal",
    "EVS",
    "General English",
    "Intro to Law",
    "Economics",
    "Political Science",
    "Contract II",
    "History",
    "Law of Crimes",
    "Environmental Law",
    "Family Law",
    "Company Law",
    "Labour Law",
    "Law of Evidence",
    "Administrative Law",
    "Human Rights",
    "Child and Law",
    "Land Law",
    "DPC",
    "Trademark Law",
    "Law Medicine",
    "International Trade Law",
    "Taxation",
    "Professional Ethics",
  ],
  subjectToDisplayName: {
    "K/F": "Konkani/French",
    CK: "Communicative Konkani",
    CF: "Communicative French",
    Konk: "Konkani",
    ATL: "ATL Lab",
    WE: "Work Education (WE)",
    MA: "Martial Arts (MA)",
    LS: "Life Studies (LS)",
    Comp: "Computers",
    Eng: "English",
    SD: "Speech & Drama",
    SS: "Social Science",
    "H&W": "Health & Wellness",
    CH: "Communicative Hindi",
    GK: "General Knowledge (GK)",
    PE: "Physical Education (PE)",
    CE: "Communicative English",
    EP: "Edu Park",
    BG: "Board Games",
  },
  classes: ["1st Year", "2nd Year", "3rd Year", "4th Year", "5th Year"],
};
