module.exports = {
  subjectList: [
    "Math",
    "Mental Math",
    "Eng",
    "CE",
    "Hindi",
    "CH",
    "Konkani",
    "CK",
    "French",
    "CF",
    "Science",
    "Science Lab",
    "EVS",    
    "History",
    "Geography",
    "Political Science",
    "PE",
    "Games",
    "Yoga",
    "MA",
    "Art",
    "Music",
    "Comp",
    "Library",
    "SD",
    "Dance",
    "EP",
    "BG",
    "Play",
    "Activity",
    "STEAM",
    "ATL",
    "WE",
    "GK",
    "LS",
    "H&W",
  ],trSubjectList: [
    "Class Teacher",
    "Co-Teacher",
    "Math/MM",
    "English/CE",
    "Hindi/CH",
    "Konkani/CK",
    "French/CF",
    "Science/Sci Lab",
    "JSL",
    "SS",
    "PE",
    "Yoga",
    "MA",
    "Art",
    "Music",
    "Computer",
    "Library",
    "SD",
    "Dance",
    "STEAM",
    "ATL",
    "WE",
    "GK",
    "LS",
    "H&W",
  ],
  subjectToDisplayName: {
    "K/F": "Konkani/French",
    CK: "Communicative Konkani",
    CF: "Communicative French",
    Konk: "Konkani",
    ATL: "ATL Lab",
    WE: "Work Education (WE)",
    MA: "Martial Arts (MA)",
    LS: "Life Studies (LS)",
    Comp: "Computers",
    Eng: "English",
    SD: "Speech & Drama",
    SS: "Social Science",
    "H&W": "Health & Wellness",
    CH: "Communicative Hindi",
    GK: "General Knowledge (GK)",
    PE: "Physical Education (PE)",
    CE: "Communicative English",
    EP: "Edu Park",
    BG: "Board Games"
  },
  classes: [
    "1st Year",
    "2nd Year",
    "3rd Year",
    "4th Year",
    "5th Year",
  ],
};
