module.exports = {
  subjects: [
    "Class Teacher",
    "Math",
    "Mental Math",
    "Eng",
    "CE",
    "Hindi",
    "CH",
    "K/F",
    "CK/CF",
    "Konkani",
    "CK",
    "French",
    "CF",
    "Science",
    "Science Lab",
    "SS",
    "History",
    "Geography",
    "Political Science",
    "PE",
    "Games",
    "Yoga",
    "MA",
    "Art",
    "Music",
    "Comp",
    "Library",
    "SD",
    "Dance",
    "ATL",
    "WE",
    "GK",
    "LS",
    "H&W",
    "STEAM",
  ],
  subjectToDisplayName: {
    "K/F": "Konkani/French",
    CK: "Communicative Konkani",
    CF: "Communicative French",
    Konk: "Konkani",
    ATL: "ATL Lab",
    WE: "Work Education (WE)",
    MA: "Martial Arts (MA)",
    LS: "Life Studies (LS)",
    Comp: "Computers",
    Eng: "English",
    SD: "Speech & Drama",
    SS: "Social Science",
    "H&W": "Health & Wellness",
    CH: "Communicative Hindi",
    "CK/CF": "Communicative Konkani/French",
    GK: "General Knowledge (GK)",
    PE: "Physical Education (PE)",
    CE: "Communicative English",
  },
  classes: [
    [1, "A"],
    [1, "B"],
    [1, "C"],
    [2, "A"],
    [2, "B"],
    [2, "C"],
    [3, "A"],
    [3, "B"],
    [3, "C"],
    [4, "A"],
    [4, "B"],
    [4, "C"],
    [5, "A"],
    [5, "B"],
    [5, "C"],
    [6, "A"],
    [6, "B"],
    [6, "C"],
    [7, "A"],
    [7, "B"],
    [7, "C"],
    [8, "A"],
    [8, "B"],
    [8, "C"],
    [9, "A"],
    [9, "B"],
    [9, "C"],
    [10, "A"],
    [10, "B"],
    [10, "C"],
  ],
};
